# Generated by Django 5.1.1 on 2024-09-16 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
