# Generated by Django 5.1.1 on 2024-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
