# Generated by Django 5.1.1 on 2024-09-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0003_category_likes_category_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
